### ISSUE TITLE
How to connect with unix sockets?

### ISSUE THREAD

**Issue by tracy-ash** [mattes/gce-cloudsql-proxy-action#7]
Hi-

When I use GCP cloud_sql_proxy, I connect to it like this using SQLalchemy:

```
  CLOUD_SQL_SOCKET_DIR = "/tmp/cloudsql"
  CLOUD_SQL_CONNECTION_NAME = some-gcp-project:us-central1:my-db
   DB_QUERY = {"unix_socket": "{}/{}".format(CLOUD_SQL_SOCKET_DIR, CLOUD_SQL_CONNECTION_NAME)}

    app.config['SQLALCHEMY_DATABASE_URI'] = sqlalchemy.engine.url.URL(
        drivername="mysql+pymysql",
        username=DB_USER,
        password=DB_USER,
        database=DB_NAME,
        query=DB_QUERY,
    )
```
but this action uses '/tmp' as it's directory

I guess this is more of a Github Action question, but in order to connect using the /tmp directory later in the job, what should CLOUD_SQL_SOCKET_DIR be?

**Comment by mattes** [comment]
The implementation of this proxy is currently lacking support for unix sockets.

**Comment by tracy-ash** [comment]
Ah, ok. Thanks for the reply

Do you have any idea how difficult it would be to add support for unix sockets?  I may try to tackle this if it's not too difficult

**Comment by mattes** [comment]
Looking at the [docs](https://github.com/GoogleCloudPlatform/cloudsql-proxy#unix-socket-example) it should be possible by:

1. [Mounting](https://github.com/mattes/gce-cloudsql-proxy-action/blob/145471ad36a0211ca4a7b90af14587bcc35b3c99/action.yml#L36) unix socket under `/tmp/gce-cloudsql-proxy/<INSTANCE_CONNECTION_NAME>`
2. Updating [`-instances`](https://github.com/mattes/gce-cloudsql-proxy-action/blob/145471ad36a0211ca4a7b90af14587bcc35b3c99/action.yml#L41) to `-instances=<INSTANCE_CONNECTION_NAME>` (you'll probably have to update the [-dir /tmp](https://github.com/mattes/gce-cloudsql-proxy-action/blob/145471ad36a0211ca4a7b90af14587bcc35b3c99/action.yml#L40) as well).
3. Make the [`wait-for-it.sh`](https://github.com/mattes/gce-cloudsql-proxy-action/blob/145471ad36a0211ca4a7b90af14587bcc35b3c99/action.yml#L43-L54) logic work for unix sockets.
4. Update the [inputs](https://github.com/mattes/gce-cloudsql-proxy-action/blob/145471ad36a0211ca4a7b90af14587bcc35b3c99/action.yml#L8) to reflect the new configuration variable.

Something along the lines :-)

**Comment by tracy-ash** [comment]
I was able to get it to work by installing and running cloud_sql_proxy directly. 

      - name: Download & Start Google Cloud SQL Proxy
        shell: bash
        run: |

          wget "https://storage.googleapis.com/cloudsql-proxy/v1.21.0/cloud_sql_proxy.linux.amd64" -q -O cloud_sql_proxy
          chmod +x cloud_sql_proxy

          ./cloud_sql_proxy \
            -dir=/tmp/cloudsql \
            -instances=project:us-central1:my-fb &

**Comment by mattes** [comment]
Nice. Closing this ticket.
